name: spokewrench-install
on: [pull_request, pull_request_review, workflow_dispatch]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: create conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          channels: conda-forge,bioconda,defaults
          architecture: x64
          environment-file: environment.yml
          activate-environment: spokewrench
          auto-activate-base: false
      - name: install spokewrench
        shell: bash -el {0}
        run: pip install --editable .
      - name: test install of spokewrench rotate
        shell: bash -el {0}
        run: spokewrench -h

  test-rotate-end-to-end:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
    steps:
      - name: run rotate test
        shell: bash -el {0}
        run: |
          tests/rotate/test-rotate-end-to-end.sh tests/rotate/input/input.fasta tests/rotate/input/guide-positions.tsv \
            tests/rotate/input/guide-fractions.tsv tests/rotate/expected tests/rotate/actual
